{{- if .Values.OpenServiceMesh.enableFluentbit }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-configmap
  namespace: {{ include "osm.namespace" . }}
data:
  fluent-bit.conf: |-
    [SERVICE]
      Flush             5
      Daemon            off
      Log_Level         info
      Parsers_File      parser.conf
    [INPUT]
      Name    tail
      Tag     kube.*
      Path    /var/log/containers/osm-controller-*_{{ include "osm.namespace" . }}_osm-controller-*.log
      Parser  cri
      Read_from_Head  on
    # Identify and re-tag logs running on moby/containerd cluster (i.e., not kind/cri-o) that have level info. Effectively filters on container runtime as well as log level
    [FILTER]
      Name          rewrite_tag
      Match         kube.*
      Rule          log \\"level\\":\\"info\\" {{ .Values.OpenServiceMesh.fluentBit.logLevel }} not-kind false
    # Match only logs from new tag above. Apply k8s filter to it - this will remove the extra json nesting and format the logs exactly like they are on cri-o clusters
    [FILTER]
      Name             kubernetes
      Match            not-kind
      Merge_Log        On
      Keep_Log         Off 
    # Keep_Log breaks on kind cluster because it removes the logs themselves before the matching can occur
    # but without it it doesn't work on a non kind cluster because there are two keys named "log" which makes it impossible to match using grep
    # If we use Merge_log_key to change the key name, it nests an extra level so that doesn't help either
  # Current status: the k8s filter merge log situation works until you re-tag. Once retagging is done, it breaks and also does not annotate logs correctly. It also doesn't work because now if you use match * on the output, it matches thingsg that are a different log level also
  # The point: the merge log functionality would make logs look more consistent in the output. also, for cri-o clusters, logs can go directly to the grep step and shouldn't have to go through multiple modifies
  # In summation: this can use more work if we see issues arise with the modify filters currently being used but will require further work to make this actually save fluent bit steps
    # Grep filter to be used by cri-o logs
    [FILTER]
      name       grep
      match      kube.*
      regex      log /"level":"info"/
    # Annotate all logs with controller pod name
    [FILTER]
      Name           modify
      Match          *
      Remove         keep
      Add            controller_pod_name ${CONTROLLER_POD_NAME}
    [OUTPUT]
      Name    {{ .Values.OpenServiceMesh.fluentBit.outputPlugin }}
      Match   *
      {{- if eq (.Values.OpenServiceMesh.fluentBit.outputPlugin | lower) "azure" }}
      Customer_ID {{ .Values.OpenServiceMesh.fluentBit.workspaceId }}
      Shared_Key {{ .Values.OpenServiceMesh.fluentBit.primaryKey }}
      {{- end }}

  parser.conf: |-
    [PARSER]
      # http://rubular.com/r/tjUt3Awgg4
      Name    cri
      Format  regex
      Regex   ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z
{{- end }}
